mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('pools/',include('pools.urls')),
    path('admin/', admin.site.urls),
]

pools/urls.py
from django.urls import path
from . import views

app_name = 'pools'
urlpatterns = [
   
   path('',views.index, name="index"),
   path('<int:question_id>/',views.detail, name="detail"),
   path('<int:question_id>/results/',views.results,name="results"),
   path('<int:question_id>/vote/',views.vote,name="vote"),
   path('people/',views.voter,name="people"),
   
]

pools/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text


	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
		


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

class Voters(models.Model):
	voter_name = models.CharField(max_length=100)
	voter_id = models.CharField(max_length=100)

	def __str__(self):
		return self.voter_name

pools/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse

from .models import Question, Choice, Voters

# Create your views here.
def home(request):
	return render(request,'pools/home.html')


def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	context={'latest_question_list':latest_question_list}
	return render(request,'pools/index.html',context)
def detail(request, question_id):
	question = Question.objects.get(pk=question_id)
	#return HttpResponse("You're looking at question %s."%question_id)
	
	return render(request, 'pools/detail.html', {'question':question})

def results(request,question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request,'pools/results.html', {'question':question})

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request,'pools/detail.html',{
			'question':question,
			'error_message':'Invalid choice.'
			})
	else:
		selected_choice.votes+=1
		selected_choice.save()
		return HttpResponseRedirect(reverse('pools:results', args=[question.id,]))

def voter(request):
	if request.method == "POST":
		voter_name = request.POST['VoterName']
		voter_id = request.POST['VoterId']
		votr = Voters.objects.create(voter_name=voter_name,voter_id=voter_id)
		votr.save();
		users = Voters.objects.all()
		return render(request,'pools/home.html',{'users':users})
	else:
		return render(request,'pools/people.html')
		

		
		
		
		

pools/templates/pools/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_mssage %}<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'pools:vote' question.id %}" method="POST">
	<!--csrf stands for cross site request forgeries-->
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
	<label for="choice{{ forloop.counter }}">
		{{ choice.choice_text }}<br>
	</label>
{% endfor %}
<input type="submit" value="vote"><br>

	
</form>

pools/templates/pools/home.html
<h1>Welcome to User info</h1>
<ol>
{% for data in users %}
<li>Name: {{data.voter_name}}       Id: {{data.voter_id}}</li>
{% endfor %}
</ol>
<a href="{% url 'pools:people' %}">Back</a>

pools/templates/pools/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>index</title>
	<link rel="stylesheet" type="text/css" href="{% static 'pools/style.css' %}">
</head>
<body>

	{% if latest_question_list %}
	<ul> 
	{% for question in latest_question_list %}
	  	<li><a href="{% url 'pools:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	 <p>No polls are available.</p>
{% endif %}
	<!--
	{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/pools/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}-->


</body>
</html>

pools/templates/pools/people.html
<!DOCTYPE html>
<html>
<head>
	<title>Voter</title>
</head>
<body>

<form action="{% url 'pools:people' %}" method="POST">
	{% csrf_token %}
	<input type="text" name="VoterName" placeholder="votername"><br>
	<input type="text" name="VoterId" placeholder="voterid"><br>
	<input type="submit" value="create"><br>
	
</form>

</body>
</html>

pools/templates/pools/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'pools:detail' question.id %}">Vote again?</a>